### ISSUE TITLE
wget line is wrong

### ISSUE THREAD

**Issue by lifeisstillgood** [coderofsalvation/kanban.bash#1]
currently the linw wget in README pulls down the HTML version not the raw bash

change to ::

wget "https://raw.githubusercontent.com/coderofsalvation/kanban.bash/master/kanban"

Sorry - not enough time to do apolite pull request.

**Comment by lifeisstillgood** [comment]
also
touch .kanban.csv

**Comment by coderofsalvation** [comment]
thx committed.
