### ISSUE TITLE
Using square brackets are not supported

### ISSUE THREAD

**Issue by janhh** [coderofsalvation/kanban.bash#11]
The line `sed -i "s|$item|$(cat $TMP.update | tail -n1)|g" $KANBANFILE` does nothing if attempting to update $item with "[" and "]". I was bitten by this first time trying to update an item which accidentally had square brackets.

**Comment by coderofsalvation** [comment]
PR anyone (or maintainer-request anyone)?

**Comment by coderofsalvation** [comment]
thx! this was fixed in b907510
