### ISSUE TITLE
Can't update item if $EDITOR variable isn't set

### ISSUE THREAD

**Issue by janhh** [coderofsalvation/kanban.bash#12]
Could probably use `EDITOR=${EDITOR:-"nano"}`  somewhere on top of the script, and exit in case $EDITOR isn't set and nano isn't available. But [apparently there is also a $VISUAL environment variable](https://unix.stackexchange.com/a/4861) to consider.

**Comment by coderofsalvation** [comment]
could anyone do a PR?

**Comment by coderofsalvation** [comment]
thx, fixed in d8ab453
