### ISSUE TITLE
Add comments?

### ISSUE THREAD

**Issue by jimmysjolund** [coderofsalvation/kanban.bash#18]
The kanban solutions I have used so far I often use the comments sections to document for instance progress. Have a comments section been discussed before? Would it be possible to include in a future release or are there any reasons not to do it?

**Comment by coderofsalvation** [comment]
This is also a nice idea.
Again I think the most important task is to suggest how/where the user could specify/modify this.

**Comment by leeand00** [comment]
I would probably just add it as a CSV with a bunch of \n's in it for new lines. (but not actual new lines).

**Comment by coderofsalvation** [comment]
Ok, I've played around with several approaches. Storing it inside the CSV became pretty hairy (linebreaks inside comments etc), so I've decided for this simple workflow:

```
$ echo -e "hello\nworld" > my_idea.txt
$ kanban add TODO note my_idea.txt
$ kanban list
  id  status   tag        description
  -   -        -          -                                                                                                                                                                -
  4   TODO  note      sentry audit   
$ k 4
# OPTIONAL: if description is a file, it will open an editor and open the file (my_idea.txt)
# open an editor to update the (csv) status / description etc (as usual)
```

I'm still testing this new feature, and will push it live very soon

**Comment by coderofsalvation** [comment]
It's pushed to master! you can check it out, let me know in case of questions.
