### ISSUE TITLE
Add labels as colours?

### ISSUE THREAD

**Issue by jimmysjolund** [coderofsalvation/kanban.bash#19]
I don't know enough to implement it myself, but have a need and idea to be able to add labels to tasks and get them colour-coded to easier distinguish between different kind of tasks and/or projects on the board. For instance I would use:
red = blocked
yellow  = deadline
other colours for different projects.

**Comment by coderofsalvation** [comment]
Cool idea.
Any ideas how/where the user could specify the colors?

**Comment by coderofsalvation** [comment]
I've played a bit with colors, but this screws up the layout (it relies on unix tools `pr` and `column` which count chars, including (color) escape codes :/)
I'm closing this until somebody finds an easier solution.

**Comment by coderofsalvation** [comment]
![image](https://user-images.githubusercontent.com/180068/135603167-332e4cb1-abd2-4b8d-8651-ca5c2868402d.png)

found a way to post-process the coloring :)
coming in the future: define colors in config-file

**Comment by dverbeeck** [comment]
What ever happened to this feature? This little tool seems great, but usage is slightly confusion. For example, where you give the examples there are a few that lack any explanation of what they are intended to do

**Comment by coderofsalvation** [comment]
Hi, good question.
What we have right now is color-substitution.
In other words, we have few colors defined in the top of the script:

```
COL1="\033[37;1m"
COL2="\033[91;1m"
COL3="\033[91;5m"
```
and later in the script we use that color when it matches a certain regex:


* `#foo` will trigger `#([a-zA-Z0-9_\.-]+)` which to apply COL1
* `*bar*` will trigger `/\*([a-zA-Z0-9_\.-]+)\*/` which will apply COL3

in theory we could move this to the `.kanban/.kanban.conf` conf-file, something like this:

```
colorize["#([a-zA-Z0-9_\.-]+)"] = $RED
colorize["\*([a-zA-Z0-9_\.-]+)\*"] = $BLUE
colorize["warning"] = $RED
```

WDYT?

* word

**Comment by kevin-gwyrdh** [comment]
Very useful!!
Had a grand time working out how it works. Partially succesfully :-)

**Comment by coderofsalvation** [comment]
it's a bit clunky I know :)
Let me know if you have tips to improve this.
