### ISSUE TITLE
Support for local config files

### ISSUE THREAD

**Issue by tschoppi** [coderofsalvation/kanban.bash#2]
Currently, only one global config file in the home directory is supported.

I think it would be nicer if the user has the option of actually modifying local configurations, as different projects make use of different lists, based on the work flow differences. 

> Example: At work I have two projects that differ slightly: One would need a larger amount of backlog lists for fine-grained control of priorities, while the other one works fine with the default settings.
> For my personal kanban I don't need the `HOLD` and `CODE` sections and would like to rename the others.

As this local file behavior is already implemented for the CSV file, it should not be too much of a problem to adapt this for the config file.

**Comment by coderofsalvation** [comment]
alias k="KANBANFILE=~/.kanban.foo.csv kanban"

iirc you can just specify different kanbanfiles like this.
Not sure if that's mentioned in README.md but it is mentioned in the file itself.

ould that help?

**Comment by tschoppi** [comment]
While I do need different kanban files (which are related to content) I would also like to be able to specify the configuration file (which stores the section names used in the kanban). 

For example:

    alias k="KANBANCONF=./.kanban.conf kanban"

**Comment by coderofsalvation** [comment]
good point.
I just updated the latest version with `KANBANCONF` support for this:

    KANBANFILE=~/.kanban.foo.csv KANBANCONF=~/.kanban.foo.conf kanban show

you can use this in an alias too.

# idea

Actually i was thinking a bit on this, and maybe context-awareness would be great.
In theory this could work as well:

    alias k='KANBANFILE=./.kanban.csv KANBANCONF=./.kanban.conf kanban show'

So if you would enter a directory with a `.kanban.csv` and `.kanban.conf` file, it would automatically be used (otherwise they will be created).

**Comment by tschoppi** [comment]
Glad to be some source of inspiration :)

And thanks for the changes! :+1:
