### ISSUE TITLE
Sort in columns?

### ISSUE THREAD

**Issue by jimmysjolund** [coderofsalvation/kanban.bash#20]
I usually do a prioritization of my boards where the top task in each column is the most important one. In Kanban.bash it seems the order will always be the order the tasks were created. Would it be possible to be able to sort tasks in the columns? I suppose I could move rows around manually in the csv file but that quickly becomes complicated as the file grows.

**Comment by coderofsalvation** [comment]
Good point. 
I guess a default sort would be possible.
Any suggestions where to specify & modify the task-weights?
I guess we want this to be easier than editing the CSV.
