### ISSUE TITLE
Change statuses for one KANBANFILE?

### ISSUE THREAD

**Issue by leeand00** [coderofsalvation/kanban.bash#25]
Is it possible to change the statuses for individual KANBANFILEs?

**Comment by leeand00** [comment]
I've been heavily utilizing the KANBANFILE variable to switch project contexts.

**Comment by coderofsalvation** [comment]
not sure if I totally understand your scenario, but here are some ideas:

1. you could utilize the PROMPT_COMMAND feature of bash.
It basically runs a function everytime you run a command.
You could trigger a function which tests for a kanban file, and export variables (KANBANFILE e.g.) accordingly

2.  KANBANFILE env-var is not needed when a .kanban.csv file is present in the current working dir

**Comment by coderofsalvation** [comment]
ok with the latest release this is much easier, things are now residing in a `.kanban` folder (in homedir or current dir):

```
$ k add DOING feature "lorem ipsum"              # this gets stored in ~/.kanban/.kanban.csv
$ cd myproject
$ kanban init                                                     # myproject/.kanban directory is created with .kanban.csv and .kanban.conf
$ k add DOING feature "lorem ipsum"              # this gets stored in myproject/.kanban/.kanban.csv
```

> NOTE: if all goes fine, the latest version will detect `~/.kanban.csv` and `~/.kanban.conf` and will put it into `~/.kanban`
