### ISSUE TITLE
Incorrect behavior when not using tags from the beginning

### ISSUE THREAD

**Issue by aleksandar-todorovic** [coderofsalvation/kanban.bash#3]
Okay, so I've just installed this tool and did the following:
1. Created a couple of tasks without a tag.
2. Created a task with a tag.

**Expected behavior:** Everything to be working correctly.

**Real behavior:** Those tasks that I initially created didn't have a tag field in a CSV file, while the tags I've created with a tag had it. As a result, `kanban show` returned the name of the tag as a description of the tasks with a tag.

**Workaround:** Simply adding a blank field in the tasks that I've initially created without using tags did the trick. Everything's working fine since then.

**Comment by coderofsalvation** [comment]
PR anyone (or maintainer-request anyone)?
