### ISSUE TITLE
bug: not helpful when missing $EDITOR

### ISSUE THREAD

**Issue by prenex** [coderofsalvation/kanban.bash#32]
STEPS:
- Tried to "kanban 1" (editing of id 1) on a machine where $EDITOR was not set.

EXPECTED:
- Some error message that is meaningful for missing variable

HAPPENS:
- Some cryptic error message. I found out that this was missing by guesswork.

I understand that you pretty much best have that set anyways, but it would be helpful to add a better message. Show, init, etc. usually works (I have this "tput: unknown terminfo capability 'normal'" other error though, but everything seems to work with it).

SOLUTION:
- Add EDITOR env var on your machines
- But would be nice if software tells us.

**Comment by rubytes** [comment]
tried export EDITOR=vim should work?
I still get the same error

**Comment by coderofsalvation** [comment]
latest version adds a check for this, and displays:

```
warning: EDITOR env-variable not set: add it ('export EDITOR=vim' e.g.) to ~/.profile e.g.)
```
