### ISSUE TITLE
tput: unknown terminfo capability 'normal'

### ISSUE THREAD

**Issue by kuchtamartin** [coderofsalvation/kanban.bash#37]
`tput: unknown terminfo capability 'normal'`

Appears after every invocation.

```
$ uname -a
Linux m4ch1n4 5.4.38-gentoo #2 SMP Fri Jun 5 14:48:09 2020 x86_64 Intel(R) Core(TM) i5 CPU 660 @ 3.33GHz GenuineIntel GNU/Linux
```

```
$ env | grep term
TERM=xterm-256color
```

**Comment by ledeniz** [comment]
Same for me

```
$ uname -a
Linux C352 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ env | grep term
TERM=xterm-256color
```

**Comment by sjas** [comment]
coming probably from https://github.com/coderofsalvation/kanban.bash/blob/master/kanban#L193

**Comment by LittleMonkeyMojo** [comment]
Changing line #193 from:
  'tput cnorm  -- normal'
to:
  'tput cnorm'

fixed the issue for me.  I've tried a decent number of regular terminals and the original fails with all.

**Comment by coderofsalvation** [comment]
Thanks for reporting. this has been solved in the latest version.
