### ISSUE TITLE
Feature request: Import from Trello

### ISSUE THREAD

**Issue by schvabodka-man** [coderofsalvation/kanban.bash#4]
Hey! I think that would be nice if this app will have possibility to import from trello. ATM trello has [ REST API [](https://developers.trello.com/advanced-reference) so it wouldn't be that hard to implement that. It would help to save a time to someone who used trello and want now kanban in unix-way

**Comment by coderofsalvation** [comment]
i love trello too.
I use hubot for commenting on trello tickets on slack, but i agree a bash-client would make a great unix-doorway to trello too.
In theory we could make the backend swappable (csv vs trello-apikey).
Definately will keep it in mind, but right now im kinda swamped.

**Comment by coderofsalvation** [comment]
PR anyone (or maintainer-request anyone)?
