### ISSUE TITLE
Mishandling paths with spaces

### ISSUE THREAD

**Issue by svHatch** [coderofsalvation/kanban.bash#41]
When `./kanban init` is run within a directory that has spaces in it's path the script does not properly handle path formatting.

`
anon@domain:~/USB STICK/kanban$ k init
mkdir: cannot create directory ‘/home/user/USB/.kanban’: No such file or directory
/home/user/bin/kanban: line 133: /home/user/USB/.kanban/.kanban.conf: No such file or directory
touch: cannot touch '/home/user/USB/.kanban/.kanban.csv': No such file or directory
tput: unknown terminfo capability 'normal'
`
It attempts to run on the path up to the space: `/home/user/USB` instead of the full path: `/home/user/USB\ STICK/`

**Comment by jlockard** [comment]
That makes no sense.  It's certainly not a feature.  If you feel it's a feature, please enlighten us what the exact feature is.  You should be able to treat paths with spaces in them by properly using variables.  Even in bash.

**Comment by coderofsalvation** [comment]
this is solved in the latest version
