### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by marcus-downing** [coderofsalvation/kanban.bash#8]
Depending on the size of your terminal, some issue titles may be too long for a column on `kanban show` and are truncated. It would be nice if they could wrap to the next line instead.

**Comment by coderofsalvation** [comment]
PR anyone (or maintainer-request anyone)?

**Comment by coderofsalvation** [comment]
I've looked at this, and eventhough I personally prefer the wrap (promote readability by default), I'm afraid that this is due to the nature of the `column` linux command.

I would suggest you inspect the particular column (DOING e.g.) like this:

    $ kanban show DOING

That way issue titles are displayed fullscreen.
