### ISSUE TITLE
Issues with commas in description

### ISSUE THREAD

**Issue by Gumnos** [coderofsalvation/kanban.bash#9]
If a description has a comma, it throws off the `list` function:

    $ mv ~/.kanban.csv{,.orig} # optionally rename existing file to start fresh
    $ ./kanban add BACKLOG petstore "pet Spot, Rex, and Fluffy"
    $ ./kanban list
    id  status   tag       description  history
    -   -        -         -            -
    2   BACKLOG  petstore  pet Spot      Rex
    1   status   tag       description  history

Notice how " Rex" is under the `history` column

**Comment by coderofsalvation** [comment]
PR anyone (or maintainer-request anyone)?

**Comment by coderofsalvation** [comment]
fixed in 7d53fe9
